name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 1.5.4
publish_to: none
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter_core: ^1.5.3
  stream_chat: ^1.5.3
  photo_view: ^0.11.0
  rxdart: ^0.25.0
  http_parser: ^3.1.4
  scrollable_positioned_list: ^0.1.8
  jiffy: ^3.0.1
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_portal: ^0.3.0
  cached_network_image: ^2.5.0
  shimmer: ^1.1.2
#  flutter_markdown: ^0.5.2
  flutter_markdown:
    git:
      url: https://github.com/apurvbacancy/packages.git
      path: packages/flutter_markdown
  url_launcher: ^5.7.10
  emojis: ^0.9.3
  video_player: ^2.0.0
  chewie: ^1.0.0
  file_picker: ^2.1.5
  image_picker: ^0.6.7+17
  flutter_keyboard_visibility: ^4.0.2
  video_compress: ^2.1.1
  visibility_detector: ^0.1.5
  meta: ^1.2.4
  lottie: ^1.2.1
  archive: ^3.1.6
  uuid: ^3.0.5
  crypto: ^3.0.0
  args: ^2.3.0
  substring_highlight: ^0.1.2
  flutter_slidable: ^0.5.7
  image_gallery_saver: ^1.6.7
  share_plus: ^1.2.0
  mime: ^0.9.7
  photo_manager: ^1.0.0
  ezanimation: ^0.4.1
  synchronized: ^2.1.0
  characters: ^1.0.0
  dio: ^3.0.10
  path_provider: ^1.6.27
  video_thumbnail: ^0.2.5+1
  flutter_screenutil: 1.0.2

dependency_overrides:
  lottie: ^1.2.1
  archive: ^3.1.6
  uuid: ^3.0.5
  crypto: ^2.0.0
  args: ^2.3.0
  share_plus: ^1.2.0
  mime: ^0.9.7
  dio: ^3.0.10
  rxdart: ^0.25.0
  http_parser: ^3.1.4
  flutter_svg: ^0.21.0-nullsafety.0
flutter:
  assets:
    - images/
    - assets/icons/
    - svgs/
    - lib/svgs/
    - animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/roboto_regular_fonts.ttf
          weight: 400
        - asset: assets/fonts/roboto_medium_fonts.ttf
          weight: 500
        - asset: assets/fonts/roboto_bold_fonts.ttf
          weight: 600
        - asset: assets/fonts/roboto_black_fonts.ttf
          weight: 700
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  pedantic: ^1.9.2